### ISSUE TITLE
Spam flood despite captcha

### ISSUE THREAD

**Issue by holzfelix** [einpraegsam/powermailrecaptcha#14]
I activated and integrated the captcha. It is also displayed. Unfortunately I had a flood of spam today.

Problem could be that you can send the form (at least some) without filling in the captcha. 

The captcha is created. sitekey / secret set. It is marked as a mandatory field. 

If it doesn't work you can send the form without captcha.

What could be the reason?

I run typo3 8.7.24 latest powermail and latest captcha

Thanks in advance.

**Comment by holzfelix** [comment]
found the issue. can be closed. typoscript issue.

**Comment by schuberttobias** [comment]
@holzfelix Could you please provide more details on your fix? I am facing the same issue: The form can be sent even if the captcha is not solved/filled.

**Comment by schuberttobias** [comment]
I was able to make it work in the end: spamshield needs to be enabled:
plugin.tx_powermail.settings.setup.spamshield._enable = 1

In my case, this was set to 0 in some Typo3 Template which I overlooked.

After enabling spamshield, submitting the powermail form now only works if the captcha is solved!
