### ISSUE TITLE
Support for TYPO3 v10

### ISSUE THREAD

**Issue by Chrisswald** [einpraegsam/powermailrecaptcha#15]
Do you plan an update of your extension in the near future?

**Comment by taurec76** [comment]
I tested it with version 10 and it looks like only the public function needs the return types to be added.
I will test it a bit more, but maybe this helps to refresh the extension for version 10

**Comment by Nesfiran** [comment]
Dear Support Team,
is there more information if a Typo3 V10 release is available in the near future?

Or will the support for V10 be discontinued?

Many greetings

**Comment by sbusemann** [comment]
@einpraegsam this can be closed

**Comment by einpraegsam** [comment]
Thx @sbusemann - will close it
