### ISSUE TITLE
Support for powermail 7.4.0?

### ISSUE THREAD

**Issue by schuberttobias** [einpraegsam/powermailrecaptcha#17]
Is powermail 7.4.0 supported and tested?

In [Readme.md](https://github.com/einpraegsam/powermailrecaptcha/blob/master/README.md) it says: 

> Dependencies
>    powermail >= 5.0 and **<** 7.0

In [composer.json](https://github.com/einpraegsam/powermailrecaptcha/blob/master/composer.json#L21) it says:
> "in2code/powermail": ">=5.0.0 <8.0.0"

**Comment by georgringer** [comment]
it worked for me FYI

**Comment by schuberttobias** [comment]
@georgringer thank you for the feedback.

I was able to make it work in the end: spamshield needs to be enabled:
`plugin.tx_powermail.settings.setup.spamshield._enable = 1`

In my case, this was set to 0 in some Typo3 Template which I overlooked.

After enabling spamshield, submitting the powermail form now only works if the captcha is solved!
