### ISSUE TITLE
Kein Formularfeld mit "Google Captcha" auswählbar

### ISSUE THREAD

**Issue by Webschmiede** [einpraegsam/powermailrecaptcha#2]
We have installed and configured the extension as described. Unfortunately, there is no "Google Captcha" in Powermail form fields.

We are currently using **Typo3 7.6.15** and **Powermail 3.11.1**

**Comment by einpraegsam** [comment]
Pls write in english if others have the same problem.

This lines in PageTS will add a new field type: https://github.com/einpraegsam/powermailrecaptcha/blob/master/Configuration/PageTsConfig/Recaptcha.typoscript

If there is no new fieldtype in the selection in backend: 
- Is it really not there? Try to scroll down.
- What if you add the line of PageTS manually into the page settings?

**Comment by Webschmiede** [comment]
We entered the lines into the TS. 

Now the point is visible in the drop-down - but **only if you add "field" in the list view**. In the editor for the form, the point does not appear. 

So far so good - last but not least we had to **copy the template (Recaptcha.html) into the Powermail Template folder**  and now it works.

Thanks for the quick support...
