### ISSUE TITLE
Add extension key in composer.json

### ISSUE THREAD

**Issue by thomasrawiel** [einpraegsam/powermailrecaptcha#20]
When installing with composer we get the following message:

The TYPO3 extension package "in2code/powermailrecaptcha", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory i
n future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by einpraegsam** [comment]
Thx, just released a new version
