### ISSUE TITLE
sitekey not visible

### ISSUE THREAD

**Issue by miurazvan** [einpraegsam/powermailrecaptcha#4]
Hi there,
first of all, great work, it's really easy to install for noobs like me :D 
but I have a problem, somehow the sitekey doesn't get delivered. I pasted the key in the ext_typoscript_setup.txt file, but the frontend gives "Please register you domain.. bla bla.. plugin.tx_powermailrecaptcha.sitekey = abcdef"
I hardcoded a {settings.recaptcha.sitekey} in the < p > tag in the .html file and it outputs "abcdef", so the link to it is broken. I'm a complete beginner in typo3, and the coding world too, but I like challenges. I'm trying to understand how your code works, how typoscript works and where exactly is the value saved. If i get to the bottom of it, I will write my fix here. A bit of help understanding how it works or what I should do would be great.
Thanks!

**Comment by miurazvan** [comment]
Weirdly enough, looking in the typoscript template I can find the tx_powermailrecaptcha.sitekey, and it's the good one. But tx_powermail.settings.recaptcha doesn't exit. Even weirder, like I said, hardcoding {settings.recaptcha.sitekey} in the html outputs "abdcef". Yet the constant isn't present in the typoscript. Is typoscript that crazy, or am I?

**Comment by einpraegsam** [comment]
Hi, first of all, hardcoding values in an extension is the wrong way. How could you update the extension afterwords if you modified files before?

Just use TypoScript constants and set it:
```
plugin.tx_powermailrecaptcha.sitekey = 6LdsBBUTAAAAAKMhI67inzeAvzBh5JdRRxlCwbTz
plugin.tx_powermailrecaptcha.secretkey = 6LdsBBUTAAAAAKMhaaaainzeAvzBh5JdRRxlCwbyy
```
After that, please clear the cache and try again.

**Comment by miurazvan** [comment]
Hi.
I only hardcoded for debugging purposes, to understand how typoscript works :D 
It seems the cache clearing did it. It seems I forgot the first rule to debugging, first refresh/restart clear cache/cookies and only after none of it works, start going through code. 
Sorry for the trouble and thanks a lot!

**Comment by einpraegsam** [comment]
No problem, have fun
