### ISSUE TITLE
Multiple recaptcha on same page

### ISSUE THREAD

**Issue by Sonezi** [einpraegsam/powermailrecaptcha#5]
Hello, great work btw.
Can you help me how to add multiple recaptcha on same page.
i have tab(4) content element and first 2 tabs are powermail forms, but when i set recaptcha on both forms i get error multiple loading source on same page for recaptcha.
Is there a way to add dynamically id in template of recaptcha, then we can remove line from template for calling api and assign it to page.includeJS as external source. So we can have multiple recaptcha but one call to api.

Thanks!

**Comment by einpraegsam** [comment]
Hi, it's possible that this is a missing feature at the moment.
